### ISSUE TITLE
Bug: On windows, the test case `TestPackageCacheLock` will be failed sometimes.

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#120]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run `make cover` on windows under the project root. 

### 2. What did you expect to see? (Required)

All test cases passed.

### 3. What did you see instead (Required)

Sometimes, the test case `TestPackageCacheLock` failed.

**Comment by xudaotutou** [comment]
![图片](https://github.com/kcl-lang/kpm/assets/71751336/fa71a94c-a08c-4b49-85a1-82352b94bdc3)
Face a similar problem. I can't add packages in win11 
- version of KCL: Version: 
  - 0.5.0-alpha.1-eb2f4d1aabc2a287c298bc35c5fcfec1
  - Platform: x86_64-pc-windows-msvc
  - GitCommit: a55c820b6b0e110eb49e724a3b36eb9da62f208d
- version of KPM: 0.3.0

**Comment by zong-zhe** [comment]
> ![图片](https://user-images.githubusercontent.com/71751336/253958836-fa71a94c-a08c-4b49-85a1-82352b94bdc3.png) Face a similar problem. I can't add packages in win11
> 
> * version of KCL: Version:
>   
>   * 0.5.0-alpha.1-eb2f4d1aabc2a287c298bc35c5fcfec1
>   * Platform: x86_64-pc-windows-msvc
>   * GitCommit: a55c820b6b0e110eb49e724a3b36eb9da62f208d
> * version of KPM: 0.3.0

Hello @xudaotutou , I have fixed this issue in #127 , you can touch this fix in kpm v0.3.1
