### ISSUE TITLE
Enhancement: `kpm add` command displaying optimization

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#123]
### 

The content of the output information is different in different modes.

`<debug_info>` represents more detailed output information. For more information, see https://github.com/kcl-lang/kpm/issues/124.

### 1. Download successfully
```
$ kpm add k8s
kpm: adding dependency k8s
kpm: the latest version 1.27.2 will be pulled from 'oci://ghcr.io/xx/k8s'.
kpm: add dependency successfully.
```
```
$ kpm add k8s:1.27.2
kpm: adding dependency k8s with version 1.27.2.
kpm: the 'k8s' will be pulled from 'oci://ghcr.io/xx/k8s'.
kpm: add dependency successfully.
```

### 2. Current directory is not a kcl package.
```
$ kpm add k8s
kpm: could not find `kcl.mod` in '/xxx/xxx'. <debug_info>
```
### 3. kcl.mod parsing error
```
$ kpm add k8s
kpm: failed to load the 'xxx/xxx/kcl.mod'. <debug_info>
```

### 4. kcl.mod.lock parsing error
This file should be generated automatically, if parsing error occurs, delete and regenerate it.

### 5. Failed to load global configuration
The `kpm add` needs to download, so it needs to load the global configuration for kpm.

#### Failed to load user login information configuration.
```
$ kpm add k8s
kpm: failed to load credentials file '/xx/xx/config.json', <debug_info>
```

#### Failed to load registry information.
```
$ kpm add k8s
kpm: failed to load '/xxx/xxx/xxx/config.json', <debug_info>
```

### 6. failed to download 
```
$ kpm add k8s
kpm: adding dependency k8s with version 1.27.2.
kpm: the 'k8s' will be pulled from 'oci://ghcr.io/xx/k8s'.
kpm: failed to add dependency, cannot download 'k8s:1.27.2' from 'oci://ghcr.io/xx/k8s'. <debug_info>
```
### 7. After downloading, checksum check error.
```
$ kpm add k8s
kpm: adding dependency k8s with version 1.27.2.
kpm: the 'k8s' will be pulled from 'oci://ghcr.io/xx/k8s'.
kpm: failed to add dependency, checksum for `k8s` changed in lock file. <debug_info>
```
### 8. After downloading, failed to update kcl.mod
```
$ kpm add k8s
kpm: adding dependency k8s with version 1.27.2.
kpm: the 'k8s' will be pulled from 'oci://ghcr.io/xx/k8s'.
kpm: failed to update the package info into 'xxx/xxx/xxx/kcl.mod'. <debug_info>
```
### 9. After downloading, failed to update kcl.mod.lock
```
$ kpm add k8s
kpm: adding dependency k8s with version 1.27.2.
kpm: the 'k8s' will be pulled from 'oci://ghcr.io/xx/k8s'.
kpm: failed to update the package info into 'xxx/xxx/xxx/kcl.mod.lock'." <debug_info>
```

**Comment by amyXia1994** [comment]
Provide more perspective message, For example:
- `kpm: failed to load credentials file '/xx/xx/config.json`: -> Incomplete user login configuration. failed to load credentials file '/xx/xx/config.json


When an error occurred, it's better to provide more information about how to fix it. For example:
- `kpm: could not find `kcl.mod` in '/xxx/xxx'. <debug_info>`: + run `kpm init` to generate a kcl.mod file
- `kpm: failed to load credentials file '/xx/xx/config.json`: -> failed to load credentials file '/xx/xx/config.json. Please <do something to get correct credentials file>
