### ISSUE TITLE
Enhancement:Supports oci registry with 'http'. 

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#139]
## Enhancement
I set up an oci registry in my local environment at `http://localhost:5001` with account `test`, kpm will raise errors when interacting with this oci registry with `http`.

```
Head "https://localhost:5001/v2/test/wordpress/manifests/sha256:ad8492...": http: server gave HTTP response to HTTPS client
```

**Comment by liangyuanpeng** [comment]
So it's finished and can be closed.
