### ISSUE TITLE
support to define a package overview introduction for a kpm package

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kpm#154]
## Enhancement

We want to provide an overview introduction for our KCL package and let the package users view the introduction on the registry to gain a basic cognition of the package:

- A short overview description of the package, one sentence long.
- A comprehensive introduction to the usage, examples, and other more detailed information about the package, which may contain multimedia resources like images or videos. It may act as the homepage of the package

refs:
- the `description` and `readme` fields in cargo manifest's `[package]` section: https://doc.rust-lang.org/cargo/reference/manifest.html

**Comment by liangyuanpeng** [comment]
May related: https://github.com/kcl-lang/kcl/issues/716
