### ISSUE TITLE
Enhancement: 'kpm run' supports run the kcl package from git repo.

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#184]
## Enhancement

'kpm run' should support the compilation of kcl packages from git repo.

Examples:

```
$ kpm run git://github.com/KusionStack/catalog
```

compile with tag
```
$ kpm run --tag 0.1.0 git://github.com/KusionStack/catalog
```

**Comment by AkashKumar7902** [comment]
Hey @Peefy 
I would like to work on this. can you please assign me this issue ?
