### ISSUE TITLE
Enhancement: Add check for package version between kcl.mod and version in command

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#190]
## Enhancement
Add check for package version between kcl.mod and version in command.

The package version in kcl.mod:

```
[pacakge]
name=mykcl
version=0.1.0
edition=0.5.6
```

The package version in command
```
$ kpm add --tag 0.1.0 --git https://xxx/xxx/xx.git
```

There should be a check to make sure they are consistent.

**Comment by octonawish-akcodes** [comment]
I would like to work on this

**Comment by AkashKumar7902** [comment]
Hey @Peefy 
Will the check be performed between the value of --tag arg and version field of the manifest file ? 
I believe, the value of the --tag refers to "git repository tag" of the dependency we want to add.

**Comment by Peefy** [comment]
cc @zong-zhe

**Comment by octonawish-akcodes** [comment]
@zong-zhe I guess its b/w the package name in kcl.mod file and the -- tag version? One query, the tag is taking the image version inside it or the package version?

**Comment by zong-zhe** [comment]
Hi, @octonawish-akcodes 😃
You are welcome to participate in KCL community.

Let me add more details to this issue.

In a KCL package, the version of a package can be specified through the version field in the `kcl.mod` file.

If a KCL package is uploaded to the OCI Registry as an OCI artifact via `kpm push`, the value of this version field will be used as the version of the OCI artifact.

Taking the `k8s` package as an example,

When adding the `k8s` package from the OCI Registry as a dependency via the `kpm add` command, in the command `kpm add k8s:1.27`, the version number 1.27 is consistent with the version field in the `kcl.mod` of the downloaded `k8s` package. There is no problem with this process.

However, kpm supports using the KCL repository from public git repo as a third-party library dependency. Here, there is a problem of inconsistency between the git tag and the version field in the `kcl.mod` file in the KCL package. Because we can not control the way used by users to push the KCL package to git repo. In some cases, this may introduce security risks.

Therefore, we hope to add a check. During the process of adding dependencies or compiling, if the version field in the `kcl.mod` file cloned from the git repo is inconsistent, a warning needs to be displaying to notify the user that the git tag of the third-party library dependency actually used is different from the version number in `kcl.mod`. Of course, an environment variable switch is also needed to control whether to perform this check.

If you have any other questions, let me know. 😊😊😊

**Comment by octonawish-akcodes** [comment]
I tried to reproduce the mismatch but this command isn't adding this dependency
![image](https://github.com/kcl-lang/kpm/assets/76171953/d5ee613a-d0c5-42af-97c9-e4772e366577)


am I using the command correctly? @zong-zhe

**Comment by zong-zhe** [comment]
Hi @octonawish-akcodes, I think that there are still some misunderstandings,

Let me add some more details,

Firstly, the problem is that kpm can currently add a git repo as a dependency of a third-party dependency through a tag, but this tag may not be consistent with the version field in the `kcl.mod` of the third-party dependency. When we add a dependency from git repo, if we find that the git repo tag is inconsistent with the version field in kcl.mod of the third-party dependency, we need to displaying a warning.

It means:
If package `A` depends on package `B`, and the version field in kcl.mod of package `B` is 0.1.0, but package B comes from a git repo, and the tag of package B’s git repo is 0.2.0, which inconsistent with the version field, a warning needs to be thrown out. 

The misunderstanding in https://github.com/kcl-lang/kpm/pull/254 is checking the difference between the version field of `A` with the tag with `B`.

**Comment by zong-zhe** [comment]
Hi @octonawish-akcodes 

We have had some discussions about this issue, and there is some controversy. The content of this issue is outdated. I have created a new issue https://github.com/kcl-lang/kpm/issues/266 to provide more details. This issue will be closed soon, and the specific content will be updated in https://github.com/kcl-lang/kpm/issues/266.
