### ISSUE TITLE
[Enhancement] KPM Import Tool CLI Design

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kpm#192]
WIP

**Comment by jakezhu9** [comment]
## Overview

The KPM Import Tool can import other data and schema to KCL. It should provides users with a convenient way to convert their files from formats like JSON, YAML, and more into KCL format.

## Design

The KPM Import Tool will provide a simple and intuitive command-line interface that allows users to specify the input file and optional configuration settings.

### Command Syntax

```bash
kpm import [OPTIONS] <FILE>
```

### Options

- `--mode` or `-m`: Specifies the conversion mode.  Default value is `auto`. The following modes are supported:
  - `json`: Convert json data to kcl data.
  - `yaml`: Convert yaml data to kcl data.
  - `gostruct`: Convert go structures to kcl schema.
  - `jsonschema`: Convert json schema to kcl schema.
  - `terraformschema`: Convert terraform provider schema to kcl schema. For how to obtain terraform provider schema files, refer to [terraform schema](https://developer.hashicorp.com/terraform/cli/commands/providers/schema).
  - `auto`: Automatically detect the file type and use the corresponding conversion mode.
- `--output` or `-o`: Specifies the output file name. Default value is `generated.k`.
- `--force`or`-f`: Force overwrite of the output file.
- `--help` or `-h`: Displays help information about the tool.

### Examples

Use `kpm import` to convert yaml data to kcl data.

```
$ cat <<EOF > foo.yaml
kind: Service
name: kcl
EOF

$ kpm import foo.yaml

$ cat generated.k
"""
This file was generated by the KCL auto-gen tool. DO NOT EDIT.
Editing this file might prove futile when you re-run the KCL auto-gen generate command.
"""

kind = "Service"
name = "kcl"
```

---

I have implemented the above design in #194. If you have a better idea, comment in this issue or PR and I will improve it
