### ISSUE TITLE
kpm run file order issue

### ISSUE THREAD

**Issue by steeling** [kcl-lang/kpm#241]
### 1. Minimal reproduce step (Required)

Create the following files in a directory called `my_app`

`my_app/base.k`:

```
schema MyApp:
   name: str
   versions: {str:str}
   version = versions[name]
```

`my_app/input1.k`:

```
output = MyApp{
   name = "my-app"
   versions = my_versions
}
```

`my_app/versions.k`:
```
my_versions = {
   "my-app": "1.0.0"
}
```

### 2. What did you expect to see? (Required)

This should compile via `kpm run my_app`. However it can be fixed if we rename `my_app/versions.k`, so that it lexicographically precedes `input1.k`:

```
mv my_app/versions.k my_app/a_versions.k
kpm run my_app
``` 

This now succeeds.

### 3. What did you see instead (Required)

```
 --> my_app/base.k:4:1
  |
4 |    version = versions[name]
  |  'UndefinedType' object is not subscriptable with 'str'
  |
```

### 4. What is your KCL components version? (Required)

kpm version 0.5.0

**Comment by Peefy** [comment]
Related Issue: https://github.com/kcl-lang/kcl/issues/247

@steeling Hi there, thank you for your feedback. We are considering supporting this feature. The internal scope of the configuration block references global scope variables, which are currently not visible.

**Comment by satyampsoni** [comment]
is this issue still relevant?

**Comment by Peefy** [comment]
> is this issue still relevant?

Yes.

**Comment by satyampsoni** [comment]
can you please assign me?
@Peefy
