### ISSUE TITLE
Feature: Package Version Management for kpm

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#246]
# Feature Request

## Is your feature request related to a problem? 
Yes, currently KCL package manager lacks an efficient way to manage different versions of the same package. This makes it difficult for users to install specific versions, upgrade, or downgrade packages.

## Describe the feature you'd like
I would like to propose a version management feature for our package manager. This feature should allow users to easily view, install, upgrade, and downgrade different versions of packages. It should also handle dependencies version conflicts between different versions of the same package to ensure that all dependencies are met when installing, upgrading, or downgrading a package.

## Pretest

To apply for this mentorship, finish the pre-tests.
- Pre-test link: https://github.com/kcl-lang/kpm/issues/263
- Pre-test link: https://github.com/kcl-lang/kpm/issues/269

**Don't worry that you may not be able to complete all the pretests, you can choose any pretests you can do, and we will consider the final choice according to all your work. You can also try some other non-pretest work, after all, that will help you understand the whole project**

## Appendix

- kpm download the dependencies here : https://github.com/kcl-lang/kpm/blob/bd65b2a7cf109c3859bfd1bdfd315bc93a8e5caa/pkg/client/client.go#L1095

- When kpm downloads dependencies, it recursively adds all the dependencies of the dependencies to the current project. Here: https://github.com/kcl-lang/kpm/blob/bd65b2a7cf109c3859bfd1bdfd315bc93a8e5caa/pkg/client/client.go#L1146

- The Pre-Test https://github.com/kcl-lang/kpm/issues/263 can follow this approach https://github.com/kcl-lang/kpm/blob/bd65b2a7cf109c3859bfd1bdfd315bc93a8e5caa/pkg/client/client.go#L1095, and calculate the dependent graph during the download process.

- This issue can follow this approach https://github.com/kcl-lang/kpm/blob/bd65b2a7cf109c3859bfd1bdfd315bc93a8e5caa/pkg/client/client.go#L1095, when download different versions of the same package, design a selection strategy, select the appropriate version to download, and report an error if the appropriate version is not found.

- When you design a selection strategy,  you can refer to [golang mvs](https://go.dev/ref/mod#minimal-version-selection).

**Comment by octonawish-akcodes** [comment]
I am interested in this under lfx

**Comment by zong-zhe** [comment]
Hi @octonawish-akcodes 😄

Your enthusiasm to participate in the project is quite ahead of time. We greatly appreciate your passion. 👍 

However, the selection for the LFX project is still in progress, and we still have some preparations to make. You can refer to the specific timeline here: [LFX Project Timeline](https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2024/01-Mar-May/README.md). We will continue to update some detailed information about the KCL package manager in this issue. You can keep an eye on it. We will contact you after the project starts.

**Comment by AkashKumar7902** [comment]
Hey, I am too interested in working in this project.

**Comment by zong-zhe** [comment]
Hi @AkashKumar7902 😄

The selection for the LFX project is still in progress, and we still have some preparations to make. You can refer to the specific timeline here: [LFX Project Timeline](https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2024/01-Mar-May/README.md). We will continue to update some detailed information about the KCL package manager in this issue. You can keep an eye on it.

We warmly welcome your contribution to the KCL project. If you are interested in our project, you can also choose some other issues to work on:

KCL: The KCL Compiler - https://github.com/kcl-lang/kcl/issues
kpm: The KCL Package Management Tool - https://github.com/kcl-lang/kpm/issues

If you have any questions welcome, you can directly raise the issue or initiate a new discussion to discuss with us.
https://github.com/orgs/kcl-lang/discussions 👋

**Comment by amands98** [comment]
Hello, I'm also interested in working on this issue. We could create something like a KVM (KCL Version Manager) or add a subcommand to the kpm for updating, changing, or downgrading package versions.

**Comment by AbhishekTiwari23** [comment]
@zong-zhe 
Hi, I have a few questions like
1) Is there any pre-requisite or pre-task for this issue
2) What kind of Cover Letter do you want, like a proposal with a detailed explanation of my approach and timeline
I am asking these questions because this will be my last attempt at LFX mentorship, so I just want to choose the right project and get selected.
Thanks

**Comment by gauriimaheshwarii** [comment]
Hi, I would like to work on this issue. I do have some ideas for it, and I'll share them on the discussions page.

**Comment by kanha-gupta** [comment]
Hi @Peefy @zong-zhe, I am applying for it. If a proposal is required, please let me know :)

**Comment by zong-zhe** [comment]
Hi @octonawish-akcodes @AkashKumar7902 @amands98 @gauriimaheshwarii @kanha-gupta 😃
Welcome ! I have added some details in this issue to help everyone understand.

**Comment by partik03** [comment]
Hi @zong-zhe I would like to work on this one during the upcoming LFX term and I will apply for the same in a day or so and currently working on the pretest assigned for this issue.

**Comment by AkashKumar7902** [comment]
Hi @Peefy @zong-zhe
I have submitted a PR for the pretest. Regarding adding testsets, is there any external package including which can result in a complex dependency graph ?

I am looking forward for the LFX.

Thanks.

**Comment by AkashKumar7902** [comment]
Hey @Peefy @zong-zhe 
I have submitted the PR for pretest https://github.com/kcl-lang/kpm/pull/264. I am super excited to apply. 😀

**Comment by zong-zhe** [comment]
Hi @octonawish-akcodes @AkashKumar7902 @amands98 @gauriimaheshwarii @kanha-gupta 😃 

I added a new PreTest https://github.com/kcl-lang/kpm/issues/269，There is no dependency between these pretests, you can choose the PreTest you like to do.
