### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by satyampsoni** [kcl-lang/kpm#247]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I came to this repo and wanted to learn how to contribute to it but I could not find any contributing.md file

**Describe the feature you'd like:**

A CONTRIBUTING.md file is a document within a software project repository that provides guidelines and information for individuals who want to contribute to the project. This file serves as a reference for potential contributors, helping them understand the project's development process, expectations, and how they can effectively participate. Below is an example template for a CONTRIBUTING.md file.

I would like to work on this issue.

**Comment by zong-zhe** [comment]
Hi @satyampsoni  😃 
We warmly welcome your participation in our community. If you would like to help us solve this issue, you can directly submit a PR. We can review it together. You may refer to this document from KCL.

https://kcl-lang.io/docs/community/contribute/

All sub-projects in the project follow this contribution guide, so there’s no need to add one for each individual project. If you’d like, you can add an entry to this link in the README.md, or you can also take a look at other issues.
