### ISSUE TITLE
[LFX PreTest] Package version selection strategy research

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#269]
## Enhancement

This is LFX PreTest for https://github.com/kcl-lang/kpm/issues/246

This job is a paper work. The core of a package version management is the strategy for version selection, and mature package management tools on the market already have some version management strategies. Conduct a complete survey and technology selection, list some common version management strategies, compare their advantages and disadvantages, choose the right plan, and show your consideration in the technology selection.

You can refer to go, rust, cue, or any other programming language package manager you know.

You don't have to worry about time, you can first update the unfinished work in this issue, and by adding `WIP` in the title to indicate that the work is not completed. We will select and complete the right person according to your work situation before the deadline.

For example:
```
# [WIP] Version management strategies

## Introduction
.....

## Content
......

## Summary
......
```

When you finished this job, remove the `[WIP]` and we will review it.

**Comment by octonawish-akcodes** [comment]
whats the deadline?

**Comment by zong-zhe** [comment]
> whats the deadline?

Hi @octonawish-akcodes 

It was written in the email I received that it needs to be submitted before this deadline

` ` `
The deadline to submit this form is Tues, Feb 27, 5:00 PM PST.
` ` `

We should decide who to choose one or two days in advance. 

Don't worry, as I mentioned in the issue, you can mark the work by `[WIP]`, if you can not finished it on time, and the way we select candidates is not only based on the code, but also the whole process of a feature from analysis to design and finally implementation, and how well you know the whole project.
