### ISSUE TITLE
Enhancement: kpm fixes the order of dependencies and format in kcl.mod and kcl.mod.lock

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#333]
## Enhancement
kpm changes the order of dependencies generated in kcl.mod and kcl.mod.lock in some cases.

e.g.,

![image](https://github.com/kcl-lang/kpm/assets/22744597/8b7b9aa0-32fc-4cd8-8ab7-2be2ddc5e393)

**Comment by AkashKumar7902** [comment]
Hey @zong-zhe, 
Did you encountered this issue during the invocation of update command ?

**Comment by zong-zhe** [comment]
Hi @AkashKumar7902 😃

Yes, this problem occurs not only when updating, but also when it involves rewriting `kcl.mod`, this is because `map` in `golang` is unordered by default and may need to sort the contents of `Dependencies` in struct `ModFile` before save it to `kcl.mod`.
