### ISSUE TITLE
[LFT Term 3]: The checksum check of the three-party dependencies

### ISSUE THREAD

**Issue by zong-zhe** [kcl-lang/kpm#394]
## Enhancement

The checksum verification of the dependencies in `kpm` has not been completed, and this part needs to be redesigned and completed.

#### A paper work
- A technical proposal for common package management tools checksum checking such as cargo, npm, go. mainly includes:
- - The main purpose of checking checksum
- - Related to the checksum check function
- - To implement the checksum check, which parts need to finished
- - Combined with kpm, which functions of kpm need to add checksum
- - For the existing kpm dependencies, we need a solution that does not break compatibility for starting this feature

**Comment by anshjain16** [comment]
hey i would wish to work on this issue under lfx mentorship, are there any prerequisites or any tasks that i need to complete for the issue

**Comment by varshith257** [comment]
Hey @zong-zhe @AkashKumar7902 . Any communication channels to connect with you. I started on pretest mentioned. It will be great to connect with community too.

**Comment by AkashKumar7902** [comment]
Hey @varshith257 👋 
You can connect with us on the slack channel. https://github.com/kcl-lang/community

**Comment by HitanshuPrasad** [comment]
Looking forward to making contributions for the Fall term and possibly completing pre -test with some guidance (if needed ) :)
Thanks1

**Comment by kairveeehh** [comment]
hewyy @Peefy  is the issue still open to be worked over?

**Comment by NishantBansal2003** [comment]
Hi @zong-zhe,
Should I create a pull request for the proposal using a `README.md` file or a `docx/pdf` file?
Thank you.

**Comment by ravjot07** [comment]
Hello everyone! I'm excited to join this community and am looking forward to making contributions for the Fall term. I'm currently working on a pre-test. I'd appreciate any guidance or suggestions you can offer to help me navigate and contribute effectively. Thanks!

**Comment by zong-zhe** [comment]
Hi @NishantBansal2003 @varshith257 @Gmin2 😄 

I need these information from you until Aug 13 5:00 PM PDT

- Full name (as listed on https://mentorship.lfx.linuxfoundation.org/)
- The email address
- The GitHub handle

**Comment by NishantBansal2003** [comment]
> I need these information from you until Aug 13 5:00 PM PDT
> 
> * Full name (as listed on https://mentorship.lfx.linuxfoundation.org/)
> * The email address
> * The GitHub handle

- Full name: Nishant Bansal
- Email address: nishant.bansal.282003@gmail.com
- GitHub: https://github.com/NishantBansal2003

**Comment by Gmin2** [comment]
Full name: Mintu Gogoi
Email Address: mintu.gogoi.cd.mec22@itbhu.ac.in
Github: https://github.com/Gmin2

**Comment by varshith257** [comment]
@zong-zhe 

Full Name: Vamshi Maskuri 
Email: vamshimaskuri257@gmail.com 
GitHub : https://github.com/varshith257
